keys:
  - &admin_mtrnord age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
  - &server_worker_1 age12eg3jeyapruq5atdrpknzu7quntpql4j6qtrwgtt9adm3yf6wupqxww7je
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_mtrnord
          - *server_worker_1
